### ISSUE TITLE
Handling of "keep alive" status in the request header

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-http-server#15]
The current handling of a keep-alive status in the Http header of the request creates massive cpu load. You might want to reconsider your approach.

    // Communiate
    func communicate(remoteSocket: Socket) {
        var needKeepDoing = false
        var remainingData: Data? = nil
//        repeat {
            (needKeepDoing, remainingData) = readSend(remoteSocket: remoteSocket, startWithData: remainingData)
//        } while needKeepDoing
    }

I eliminated the loop, to make the package usable again.

**Comment by meisbedi** [comment]
I see the same problem with the version 0.1.20.

Here is what I think is happening:
 - The request opens an socket and sends the keep-alive message. This stops the server from closing the socket.
 - When another request from the same client is received, another socket is opened and kept open.
 - So each new requests opens another socket, and the number of open sockets is increasing until eventually? the open socket times out?
 - Listening to all the open sockets drives up the cpu load of the simulator/device.

**Comment by bjtj** [comment]
I fixed it in tag 0.1.23

I added `HttpServer.Features.supportKeepConnect` to enable or disable keep connect. (default `false`)

I will keep it false till the feature will be stable.

Thanks you!
