### ISSUE TITLE
onDisconnect gets called with a socketfd of -1 ->runtime error

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-http-server#3]
When there is no socket with the socketfd of any socket in the array connectedSockets, a runtime error is created.

Fix: Make sure, that a matching socket exits before it gets set to nil.

func onDisconnect(remoteSocket: Socket) {
        guard let _ = connectedSockets[remoteSocket.socketfd] else { return }
        connectedSockets[remoteSocket.socketfd] = nil
    }

**Comment by meisbedi** [comment]
This is actually a problem with thread safety. There is conflicting access to the connectedSockets array from the onConnect and the onDisconnect functions. Introducing a semaphore around the array access addresses the problem. Additionally, the closing of the socket sets the socketfd to -1. Therefore, in the current implementation, the socket will not be removed from the connected socket array, because onDisconnect is called, after the socket is closed. Proposed changes:

    let block = DispatchSemaphore(value: 1)

    func onConnect(remoteSocket: Socket) {
        let _ = block.wait(timeout: .distantFuture)
        connectedSockets[remoteSocket.socketfd] = remoteSocket
        block.signal()
        DispatchQueue.global(qos: .default).async {
            [unowned self, remoteSocket] in
            self.communicate(remoteSocket: remoteSocket)
            self.onDisconnect(remoteSocket: remoteSocket)
        }
    }

    func onDisconnect(remoteSocket: Socket) {
        let _ = block.wait(timeout: .distantFuture)
        guard let _ = connectedSockets[remoteSocket.socketfd] else { return }
        connectedSockets[remoteSocket.socketfd] = nil
        remoteSocket.close()
        block.signal()
    }

**Comment by bjtj** [comment]
I fixed it!

commit: https://github.com/bjtj/swift-http-server/commit/dfc366fd4eaf78cea02af6fe2118e28aab86a7ec

Thank you
