### ISSUE TITLE
Network function getInetAddress retrieves only local host address on device

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-http-server#6]
The getInetAddress function inside the network class retrieves the first address with the ip4 version from the list of available addresses. This is typically the localhost address. You will need to link the address version (like ip4) with the interface (en0 for Wifi) in order to be able to retrieve an actual address. I noticed this, once I moved from the simulator, where everything worked fine, to an actual device. Suddenly, event subscription was not possible anymore, and a little debugging let me to the getInedAddress function as the source for the problem.

I introduced locally a temporary fix, in order to be able to continue to test.

**Comment by bjtj** [comment]
I fixed it!

Now, hostname can be configured when creating HttpServer.

And I updated swift upnp tools to use default network address to not localhost (applied to this [commit](https://github.com/bjtj/swift-upnp-tools/commit/10584f240777681f0135c39a74b58e57e0598ce2))

commit: https://github.com/bjtj/swift-http-server/commit/2fb4952ab8ddb0a19078ed3ebb1cd61a5e9ab8da

Tag: [0.1.13](https://github.com/bjtj/swift-http-server/releases/tag/0.1.13)

Thank you!
