### ISSUE TITLE
Swift-http-server crashes, when app is sent to the background

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-http-server#8]
<img width="1384" alt="Bildschirmfoto 2021-11-25 um 17 42 08" src="https://user-images.githubusercontent.com/22547751/143478197-1f6ab06c-54fd-44cd-a592-3776103874f3.png"

<img width="787" alt="Bildschirmfoto 2021-11-25 um 17 42 28" src="https://user-images.githubusercontent.com/22547751/143478203-720ab1e2-d3e9-43be-b171-00ab9384e49c.png">
>

**Comment by meisbedi** [comment]
I found a fix. Check if a request for finishing is available, before connecting to the socket. With this change, the server does not crash, when the app is sent to the background.


    func onConnect(remoteSocket: Socket) {
        if self.finishing { return }
        self.block.wait()
        connectedSockets[remoteSocket.socketfd] = remoteSocket
        self.block.signal()
        
        delegate?.onConnect(remoteSocket: remoteSocket)
        DispatchQueue.global(qos: .default).async {
            [unowned self, remoteSocket] in
            self.communicate(remoteSocket: remoteSocket)

            self.block.wait()
            self.delegate?.onDisconnect(remoteSocket: remoteSocket)
            self.connectedSockets[remoteSocket.socketfd] = nil
            self.block.signal()

            remoteSocket.close()
        }
    }

**Comment by bjtj** [comment]
I fixed it

tag: [0.1.15](https://github.com/bjtj/swift-http-server/releases/tag/0.1.15)
- fixed: closing socket on finish

Thank you!
