### ISSUE TITLE
The readSend method exits with code 404 before the onBodyCompleted handler has run

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-http-server#9]
Looks like there is an issue with asynchronous handling of the body, because the readSend method sends a response with the default 404 code, before the handler has executed the onBodyCompleted method, that sends the response code to 200 at the end. For me it looks like that the onBodyCompleted is executed asynchronously, while the readSend method runs its course.

Every once in a while i see that a code 200 is sent.

Btw, I'm using Wireshark to monitor the network traffic.

**Comment by bjtj** [comment]
I found a case that send extra response packet (404) after the response sent.

But it was not a issue related to asynchronous but error handling logic in readSend().

I fixed the issue in tag ([0.1.16](https://github.com/bjtj/swift-http-server/releases/tag/0.1.16))

- https://github.com/bjtj/swift-http-server/commit/c4e27a667867fe43f5a7e8b61abe603be406bf6a#diff-b2103dd56f6716dbf61b92db746f7e44ba1344d6c848dc1a6d1a422f8765aa38L179-L183

Thank you!

**Comment by meisbedi** [comment]
I was not focused on the code 404 anymore, because I was busy with other aspects of my app and I also was not sure, if the http server was involved in the problem I was facing. It was not.

To illustrate the issue, I created a screenshot of the communication trace between the control point (IP address ending on 101) and a renderer (IP address ending on 14). The renderer sends time events each second. There are two things to note:

 - most of the events are answered with a response code of 404. This indicates to me, that the response is send from the http server, before the handler for the header and especially the body had the chance to set the response code to 200 after processing the header/body. In my app I ignore the header. Therefore, only the handling of the body could have an influence. Originally, my event handling was done asynchronous. This means, that the handler method of the body was returning pretty fast. The fact, that in the trace you can see only one 200 response code for 4 events is also an indication, that the issue, that you identified might not be at play here.

Additionally, I recognised, that the response code is not properly "translated", because also the response code 200 gets a "Not found" in the HTTP header, while it should be "OK".

<img width="1281" alt="Bildschirmfoto 2021-12-03 um 14 13 15" src="https://user-images.githubusercontent.com/22547751/144608405-80dac494-5076-4e95-8098-534b2b9095c1.png">

**Comment by bjtj** [comment]
Thank you for the report!

First of all, please use swift-upnp-tools tag [0.1.17](https://github.com/bjtj/swift-upnp-tools/releases/tag/0.1.17) (latest for now)
swift-upnp-tools tag 0.1.17 depends on swift-http-server [0.1.16](https://github.com/bjtj/swift-http-server/releases/tag/0.1.16) which is fixed the issue that unexpectely send extra response.

## Related Fix

### Swift Http Server

Please note the return statement in catch block.

https://github.com/bjtj/swift-http-server/blob/50cd0fa3e62c32b6c925f29d498022f072c23f97/Sources/swift-http-server/HttpServer.swift#L187-L232

I think your code is not the same with my code.

It's better you post your `readSend()` code, so that I can check what is different.

### Swift Upnp Tools

Please note the changes related to the http server, and apply it to your code if you modify source code yourself.

https://github.com/bjtj/swift-upnp-tools/blob/75b0aa31615b45ae0aebc3a7c80c4a3756f96adc/Sources/swift-upnp-tools/UPnPControlPoint.swift#L245-L254

```
            do {
                self.httpServer = HttpServer(hostname: self.hostname, port: self.port)
                guard let httpServer = self.httpServer else {
                    throw UPnPError.custom(string: "UPnPControlPoint::startHttpServer() error - http server start failed")
                }
                try httpServer.route(pattern: "/notify/**", handler: self)
                try httpServer.run(readyHandler: readyHandler)
            } catch let error{
                print("UPnPControlPoint::startHttpServer() error - error - \(error)")
            }
```

https://github.com/bjtj/swift-upnp-tools/blob/75b0aa31615b45ae0aebc3a7c80c4a3756f96adc/Sources/swift-upnp-tools/UPnPCallbackUrl.swift#L28-L33

```
    /**
     Make a Callback Url
     */
    public class func make(hostname: String, port: Int32, udn: String, serviceId: String) -> URL? {
        return URL(string: "http://\(hostname):\(port)/notify/\(udn)/\(serviceId)")
    }
```

And following issue is fixed in latest tag by chage both swift-http-server and swift-upnp-tools.

ISSUE: HTTP/1.1 202 Not Found
* resolved with:
    * I added `setStatus()` in `HttpResponse` class to resolve that issue
    * swift-upnp-tools: https://github.com/bjtj/swift-upnp-tools/commit/7cfe1de0a862988094d43e8f958e56105a552c75
        ```
        -    response.code = 200
        +    response.setStatus(code: 200)
        ```
    * swift-http-server: 
    * https://github.com/bjtj/swift-http-server/blob/50cd0fa3e62c32b6c925f29d498022f072c23f97/Sources/swift-http-server/HttpResponse.swift#L66-L69
* cause:
    * `response.code = 200` not change the status text part of firstline in response

**Comment by meisbedi** [comment]
I checked with the latest version and I keep getting the 404 status code.

<img width="1693" alt="Bildschirmfoto 2021-12-06 um 12 58 37" src="https://user-images.githubusercontent.com/22547751/144842335-f643bddd-4c9b-4e7f-a43d-b0e5caa78882.png">

**Comment by bjtj** [comment]
Can you let me check you are using the latest swift upnp tools version also?

**Comment by meisbedi** [comment]
I do.
<img width="246" alt="Bildschirmfoto 2021-12-06 um 13 15 55" src="https://user-images.githubusercontent.com/22547751/144844484-336577d0-523c-4a6f-b7ab-97147474645a.png">

The only adaptation in upnp tools I apply is the setting of the hostname to ensure, that I get the wifi address on a real device.

**Comment by bjtj** [comment]
Hmm.

If so that, I cannot understand why the callback url is different with the generated callback url format. 

UPnPControlPoint.swift

![image](https://user-images.githubusercontent.com/1907889/144845529-3ef7d711-71a2-48ea-97cd-d6f1966cefd8.png)

UPnPCallbackUrl.swift

![image](https://user-images.githubusercontent.com/1907889/144845496-b8180312-70e1-4073-8a14-98a3a0c71ff9.png)

**Comment by meisbedi** [comment]
Good point. This specific renderer is constantly sending time events, no matter if there is a subscriber or not. That might be the reason, why the renderer does not really care for the specifics in the callback url. Later, I will check the situation for other events and for an alternative renderer.

**Comment by meisbedi** [comment]
Good observation.
Same renderer, different event:
<img width="1763" alt="Bildschirmfoto 2021-12-06 um 14 05 06" src="https://user-images.githubusercontent.com/22547751/144851200-9d6a572e-4224-48d5-a516-2d24be32cf32.png">

What irritated me was the fact, that I got correct information from the event, but the response code was 404.
I reviewed the UPnP standard and the actual behaviour of the renderer is not according to the standard.

As a next step, I will check another renderer

**Comment by meisbedi** [comment]
I verified the behaviour of another renderer and this one shows the correct behaviour on his events.

But..
Unfortunately, the renderer with the questionable behaviour is the well known BubbleUpnP server. Therefore I would prefer, if there would be a way, to let get this one away with the incorrect behaviour and still send the 200 response code in the case the request contains valid information.

**Comment by bjtj** [comment]
Okay, I will find a way to handle this.

**Comment by bjtj** [comment]
Please try with swift upnp tools (tag: [0.1.19](https://github.com/bjtj/swift-upnp-tools/releases/tag/0.1.19))

I changed the router pattern to any (`/**`) so that accept any request regardless of path but SID and NOTIFY method.

Thanks!

**Comment by meisbedi** [comment]
I checked the latest combination of upnp tools (0.1.19) and http server (0.1.20) and the behaviour changed. No I get an 500 response code instead of 404.
Tomorrow I will test an alternative media renderer, that supports the same set of services. I would wait until tomorrow to see, if it actually makes sense to adapt the server side for a behaviour of the renderer, that does not conform to the standard.

**Comment by meisbedi** [comment]
testing with an alternative media renderer verified, that there are implementations, that follow the standard (not sending unnecessary events and addressing the correct callback url).

Because the "bad" renderer is actually a widely used application (BubbleUPnP Server; https://www.bubblesoftapps.com/bubbleupnpserver2/), I would prefer a workaround that would leave it to the event subscriber, to decide, if the incorrect callback url should be ignored and a 200 response code would be sent.

**Comment by bjtj** [comment]
I added a feature that is able to set http response in notification handler.

Tag: swift http server (tag: 0.1.23) & swift upnp tools (tag: 0.1.21)

**Reference code:**
- https://github.com/bjtj/swift-upnp-tools/blob/b6904a60e80f6ee6cce39405a75e329dc2de49ef/Samples/controlpoint/Sources/controlpoint/main.swift#L51-L57

e.g.)

```swift
cp.addNotificationHandler {
    (subscription, properties, error) throws in
    guard error == nil else {
        print("notification error - \(error!)")
        throw HttpStatusCode.ok // <-------- http response ok will be sent
    }
    ...
```
